### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by Sorosliu1029** [ruff-drivers/waveshare-fingerprint#1]
There is a `require('ruff-async')` in [communication.js](https://github.com/ruff-drivers/waveshare-fingerprint/blob/master/src/communication.js#L12) file, i doubt that it should be included in `package.json` for `rap install`. 
Or it is a core module in ruff and dont need to explicitly been required?

**Comment by jerry-weng** [comment]
`'ruff-async'` is a core module provided by ruff, like module `net`, `path`, etc. It is must be required explicitly.
