### ISSUE TITLE
请问贵司还在招前端实习生么，很喜欢ruff哦

### ISSUE THREAD

**Issue by ghost** [ruff-drivers/waveshare-fingerprint#2]
您好 
      不知道怎么建议你们😂冒死提了一个issue

**Comment by ghost** [comment]
打错了，不知道怎么联系你们😂😂，找到贵司的邮箱了，但是显示邮件空间已满，发的邮件被退回了。请问还有其他联系方式么。

**Comment by jerry-weng** [comment]
@xiaohangJose 你可以给 lijiaqi@nanchao.org 再发一次邮件。

**Comment by ghost** [comment]
嗯嗯，好滴。谢谢您

2017年5月22日 上午10:30，"jerry-weng" <notifications@github.com<mailto:notifications@github.com>>写道：

@xiaohangJose<https://github.com/xiaohangjose> 你可以给 lijiaqi@nanchao.org<mailto:lijiaqi@nanchao.org> 再发一次邮件。
